module.exports = [
  require('./fixtures/2_0.json'),
  require('./fixtures/2_1.json'),
  require('./fixtures/2_2.json'),
  require('./fixtures/2_3.json'),
  require('./fixtures/2_4.json'),
  require('./fixtures/2_5.json'),
  require('./fixtures/2_6.json'),
  require('./fixtures/2_7.json'),
  require('./fixtures/2_8.json'),
  require('./fixtures/2_9.json'),
  require('./fixtures/2_10.json'),
  require('./fixtures/2_11.json'),
  require('./fixtures/2_12.json'),
  require('./fixtures/2_13.json'),
  require('./fixtures/2_14.json'),
  require('./fixtures/2_15.json'),
  require('./fixtures/2_16.json'),
  require('./fixtures/2_17.json'),
  require('./fixtures/2_18.json'),
  require('./fixtures/2_19.json'),
  require('./fixtures/2_20.json'),
  require('./fixtures/2_21.json'),
  require('./fixtures/2_22.json'),
  require('./fixtures/1_0.json'),
  require('./fixtures/1_1.json'),
  require('./fixtures/1_2.json'),
  require('./fixtures/1_3.json'),
  require('./fixtures/1_4.json'),
  require('./fixtures/1_5.json'),
  require('./fixtures/1_6.json'),
  require('./fixtures/1_7.json'),
  require('./fixtures/1_8.json'),
  require('./fixtures/1_9.json'),
  require('./fixtures/1_10.json'),
  require('./fixtures/1_11.json'),
  require('./fixtures/1_12.json'),
  require('./fixtures/1_13.json'),
  require('./fixtures/1_14.json'),
  require('./fixtures/1_15.json'),
  require('./fixtures/1_16.json'),
  require('./fixtures/1_17.json'),
  require('./fixtures/1_18.json'),
  require('./fixtures/1_19.json'),
  require('./fixtures/1_20.json'),
  require('./fixtures/1_21.json'),
  require('./fixtures/1_22.json'),
  require('./fixtures/1_23.json'),
  require('./fixtures/1_24.json'),
  require('./fixtures/1_25.json'),
  require('./fixtures/1_26.json'),
  require('./fixtures/1_27.json'),
  require('./fixtures/1_28.json'),
  require('./fixtures/1_29.json'),
  require('./fixtures/1_30.json'),
  require('./fixtures/1_31.json'),
  require('./fixtures/1_32.json'),
  require('./fixtures/1_33.json'),
  require('./fixtures/1_34.json'),
  require('./fixtures/1_35.json'),
  require('./fixtures/1_36.json'),
  require('./fixtures/1_37.json'),
  require('./fixtures/1_38.json'),
  require('./fixtures/1_39.json'),
  require('./fixtures/1_40.json'),
  require('./fixtures/1_41.json'),
  require('./fixtures/1_42.json'),
  require('./fixtures/1_43.json'),
  require('./fixtures/1_44.json'),
  require('./fixtures/1_45.json'),
  require('./fixtures/1_46.json'),
  require('./fixtures/1_47.json'),
  require('./fixtures/1_48.json')
].map(({ type, typeId, valid, invalid }) => ({
  valid: valid.map(entry => Object.assign(entry, { type, typeId })),
  invalid: invalid.map(entry => Object.assign(entry, { type, typeId }))
})).reduce(function (result, next) {
  return {
    valid: result.valid.concat(next.valid),
    invalid: result.invalid.concat(next.invalid)
  }
})
